backend:
  name: git-gateway
  branch: master # nebo hlavní větev vašeho repo

media_folder: "public/uploads" # Kde budou nahrávané soubory
public_folder: "/uploads"      # URL cesta k mediálním souborům

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog" # Sem budou ukládány články
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image" }
