backend:
  name: git-gateway
  branch: master

media_folder: "public/uploads" # Folder where media files will be stored
public_folder: "/uploads"      # Public URL for the media files

media_library:
  name: simple # Optional: choose a media library if you use one

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog" # Folder where the blog posts will be stored
    create: true
    slug: "{{fields.nazev}}"
    fields:
      - { label: "Id", name: "id", widget: "string", hint: "Pořadové číslo příspěvku" }
      - { label: "Nazev", name: "nazev", widget: "string", hint: "např.: jak-napsat-blogovy-clanek" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image" }